export const MAP_LIST = [
  {
    map_name_kr: '세관(Custom)',
    map_three_path: '/tkw_map/custom/ga/dormitory/first_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Custom',
    map_id: 'CUSTOM',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/CUSTOM',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom',
        map_name_kr: '세관(Custom)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:49:15.288154+00:00',
        map_three_path: '/tkw_map/custom/ga/dormitory/first_floor.dae',
        map_id: 'CUSTOM',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom ga second floor dormitory',
        map_name_kr: '가동 2층 기숙사',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 2,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:51:15.433197+00:00',
        map_three_path: '/tkw_map/custom/ga/dormitory/second_floor.dae',
        map_id: 'CUSTOM_GA_SECOND_FLOOR_DORMITORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom na second floor dormitory',
        map_name_kr: '나동 2층 기숙사',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 2,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:52:35.483392+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'CUSTOM_NA_SECOND_FLOOR_DORMITORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom ga third floor dormitory',
        map_name_kr: '가동 3층 기숙사',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 2,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:51:34.646388+00:00',
        map_three_path: '/tkw_map/custom/ga/dormitory/third_floor.dae',
        map_id: 'CUSTOM_GA_THIRD_FLOOR_DORMITORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom ga first floor dormitory',
        map_name_kr: '가동 1층 기숙사',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 2,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:50:52.175736+00:00',
        map_three_path: '/tkw_map/custom/ga/dormitory/first_floor.dae',
        map_id: 'CUSTOM_GA_FIRST_FLOOR_DORMITORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Custom na first floor dormitory',
        map_name_kr: '나동 1층 기숙사',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 2,
        map_parent_value: 'CUSTOM',
        map_update_time: '2024-04-19T05:52:18.492473+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/first_floor.dae',
        map_id: 'CUSTOM_NA_FIRST_FLOOR_DORMITORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/CUSTOM',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '연구소(The Lab)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'The Lab',
    map_id: 'THE_LAB',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/THE_LAB',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'The Lab',
        map_name_kr: '연구소(The Lab)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'THE_LAB',
        map_update_time: '2024-04-19T05:56:51.532106+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'THE_LAB',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/THE_LAB',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '리저브(Reserve)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Reserve',
    map_id: 'RESERVE',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/RESERVE',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Reserve',
        map_name_kr: '리저브(Reserve)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'RESERVE',
        map_update_time: '2024-04-19T05:56:30.504294+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'RESERVE',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/RESERVE',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '해안선(Shoreline)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Shoreline',
    map_id: 'SHORELINE',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/SHORELINE',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Shoreline',
        map_name_kr: '해안선(Shoreline)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'SHORELINE',
        map_update_time: '2024-04-19T05:55:40.099044+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'SHORELINE',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/SHORELINE',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '산림(Woods)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Woods',
    map_id: 'WOODS',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/WOODS',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Woods',
        map_name_kr: '산림(Woods)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'WOODS',
        map_update_time: '2024-04-19T05:55:14.993679+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'WOODS',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/WOODS',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '등대(Light House)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Light House',
    map_id: 'LIGHT_HOUSE',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/LIGHT_HOUSE',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Light House',
        map_name_kr: '등대(Light House)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'LIGHT_HOUSE',
        map_update_time: '2024-04-19T05:54:47.021903+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'LIGHT_HOUSE',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/LIGHT_HOUSE',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '팩토리(Factory)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Factory',
    map_id: 'FACTORY',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/FACTORY',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Factory',
        map_name_kr: '팩토리(Factory)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'FACTORY',
        map_update_time: '2024-04-19T05:56:02.550911+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'FACTORY',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/FACTORY',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '타르코프 시내(Street of Tarkov)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Street of Tarkov',
    map_id: 'STREET_OF_TARKOV',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/STREET_OF_TARKOV',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Street of Tarkov',
        map_name_kr: '타르코프 시내(Street of Tarkov)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'STREET_OF_TARKOV',
        map_update_time: '2024-04-19T05:57:52.151384+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'STREET_OF_TARKOV',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/STREET_OF_TARKOV',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '인터체인지(Interchange)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Interchange',
    map_id: 'INTERCHANGE',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/INTERCHANGE',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Interchange',
        map_name_kr: '인터체인지(Interchange)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'INTERCHANGE',
        map_update_time: '2024-04-19T05:57:10.524637+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'INTERCHANGE',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/INTERCHANGE',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
  {
    map_name_kr: '그라운드 제로(Ground Zero)',
    map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
    map_jpg_path: '/tkw_map/custom/main/custom_img.png',
    map_depth: 1,
    map_main_image: '/tkw_map/custom/main/custom_img.png',
    map_name_en: 'Ground Zero',
    map_id: 'GROUND_ZERO',
    map_three_item_path: [
      {
        color: 'PINK',
        boxArgs: [1, 1, 1],
        position: [17.171613125156625, 0, 10.340594377946204],
        childValue: 'PMC_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
      {
        color: 'SKY_BLUE',
        boxArgs: [1, 1, 1],
        position: [6.063382195161616, 0, 11.320286508856583],
        childValue: 'SCAV_EXTRACTION_VALUE',
        motherValue: 'EXTRACTIONS',
      },
    ],
    map_jpg_item_path: [
      {
        item: 1,
      },
    ],
    map_link: '/map/GROUND_ZERO',
    map_update_time: '2024-04-19T06:02:08.776681+00:00',
    map_sub: [
      {
        map_three_item_path: [
          {
            color: 'PINK',
            boxArgs: [1, 1, 1],
            position: [17.171613125156625, 0, 10.340594377946204],
            childValue: 'PMC_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
          {
            color: 'SKY_BLUE',
            boxArgs: [1, 1, 1],
            position: [6.063382195161616, 0, 11.320286508856583],
            childValue: 'SCAV_EXTRACTION_VALUE',
            motherValue: 'EXTRACTIONS',
          },
        ],
        map_name_en: 'Ground Zero',
        map_name_kr: '그라운드 제로(Ground Zero)',
        map_jpg_item_path: [
          {
            item: 1,
          },
        ],
        map_depth: 1,
        map_parent_value: 'GROUND_ZERO',
        map_update_time: '2024-04-19T05:57:28.568058+00:00',
        map_three_path: '/tkw_map/custom/na/dormitory/second_floor.dae',
        map_id: 'GROUND_ZERO',
        map_jpg_path: '/tkw_map/custom/main/custom_img.png',
        map_link: '/map/GROUND_ZERO',
        map_main_image: '/tkw_map/custom/main/custom_img.png',
      },
    ],
  },
];
