import jpg from 'src/assets/test.png';

export const MAP_LIST = [
  {
    krName: '세관(Custom)',
    enName: 'Custom',
    value: 'CUSTOM',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/CUSTOM',
    subMap: [
      {
        krName: '세관',
        enName: 'Custom',
        value: 'CUSTOM',
        path: '/api/map/three_map/custom',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
      {
        krName: '가동 1층 기숙사',
        enName: 'Custom ga first floor dormitory',
        value: 'CUSTOM_GA_FIRST_FLOOR_DORMITORY',
        path: '/api/map/three_map/custom_ga_first_floor_dormitory',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
      {
        krName: '가동 2층 기숙사',
        enName: 'Custom ga second floor dormitory',
        value: 'CUSTOM_GA_SECOND_FLOOR_DORMITORY',
        path: '/api/map/three_map/custom_ga_second_floor_dormitory',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
      {
        krName: '가동 3층 기숙사',
        enName: 'Custom ga third floor dormitory',
        value: 'CUSTOM_GA_THIRD_FLOOR_DORMITORY',
        path: '/api/map/three_map/custom_ga_third_floor_dormitory',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
      {
        krName: '나동 1층 기숙사',
        enName: 'Custom na first floor dormitory',
        value: 'CUSTOM_NA_FIRST_FLOOR_DORMITORY',
        path: '/api/map/three_map/custom_na_first_floor_dormitory',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
      {
        krName: '나동 2층 기숙사',
        enName: 'Custom na second floor dormitory',
        value: 'CUSTOM_NA_SECOND_FLOOR_DORMITORY',
        path: '/api/map/three_map/custom_na_second_floor_dormitory',
        jpg: jpg,
        depth: 2,
        link: '/map/CUSTOM',
      },
    ],
  },
  {
    krName: '등대(Light House)',
    enName: 'LightHouse',
    value: 'LIGHT_HOUSE',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/LIGHT_HOUSE',
    subMap: [],
  },
  {
    krName: '산림(Woods)',
    enName: 'Woods',
    value: 'WOODS',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/WOODS',
    subMap: [],
  },
  {
    krName: '해안선(Shoreline)',
    enName: 'Shoreline',
    value: 'SHORELINE',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/SHORELINE',
    subMap: [],
  },
  {
    krName: '팩토리(Factory)',
    enName: 'Factory',
    value: 'FACTORY',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/FACTORY',
    subMap: [],
  },
  {
    krName: '리저브(Reserve)',
    enName: 'Reserve',
    value: 'RESERVE',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/RESERVE',
    subMap: [],
  },
  {
    krName: '연구소(The Lab)',
    enName: 'The Lab',
    value: 'THE_LAB',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/THE_LAB',
    subMap: [],
  },
  {
    krName: '인터체인지(Interchange)',
    enName: 'Interchange',
    value: 'INTERCHANGE',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/INTERCHANGE',
    subMap: [],
  },
  {
    krName: '그라운드 제로(Ground Zero)',
    enName: 'Ground Zero',
    value: 'GROUND_ZERO',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/GROUND_ZERO',
    subMap: [],
  },
  {
    krName: '타르코프 시내(Street of Tarkov)',
    enName: 'Street of Tarkov',
    value: 'STREET_OF_TARKOV',
    path: '/api/map/three_map/custom',
    jpg: jpg,
    depth: 1,
    link: '/map/STREET_OF_TARKOV',
    subMap: [],
  },
];
