export const MENU_LIST = [
  {
    value: 'MAP',
    krName: '지도',
    enName: 'Map',
    subMenu: [
      {
        krName: '세관(Custom)',
        enName: 'Custom',
        value: 'CUSTOM',
        link: '/map/CUSTOM',
      },
      {
        krName: '등대(Light House)',
        enName: 'LightHouse',
        value: 'LIGHT_HOUSE',
        link: '/map/LIGHT_HOUSE',
      },
      {
        krName: '산림(Woods)',
        enName: 'Woods',
        value: 'WOODS',
        link: '/map/WOODS',
      },
      {
        krName: '해안선(Shoreline)',
        enName: 'Shoreline',
        value: 'SHORELINE',
        link: '/map/SHORELINE',
      },
      {
        krName: '팩토리(Factory)',
        enName: 'Factory',
        value: 'FACTORY',
        link: '/map/FACTORY',
      },
      {
        krName: '리저브(Reserve)',
        enName: 'Reserve',
        value: 'RESERVE',
        link: '/map/RESERVE',
      },
      {
        krName: '연구소(The Lab)',
        enName: 'The Lab',
        value: 'THE_LAB',
        link: '/map/THE_LAB',
      },
      {
        krName: '인터체인지(Interchange)',
        enName: 'Interchange',
        value: 'INTERCHANGE',
        link: '/map/INTERCHANGE',
      },
      {
        krName: '그라운드 제로(Ground Zero)',
        enName: 'Ground Zero',
        value: 'GROUND_ZERO',
        link: '/map/GROUND_ZERO',
      },
      {
        krName: '타르코프 시내(Street of Tarkov)',
        enName: 'Street of Tarkov',
        value: 'STREET_OF_TARKOV',
        link: '/map/STREET_OF_TARKOV',
      },
    ],
  },
  {
    value: 'QUEST',
    krName: '퀘스트',
    enName: 'Quest',
    subMenu: [
      {
        krName: '프라퍼(Prapor)',
        enName: 'Prapor',
        value: 'PRAPOR',
        link: '/quest/PRAPOR',
      },
      {
        krName: '테라피스트(Therapist)',
        enName: 'Therapist',
        value: 'THERAPIST',
        link: '/quest/THERAPIST',
      },
      {
        krName: '펜스(Fence)',
        enName: 'Fence',
        value: 'FENCE',
        link: '/quest/FENCE',
      },
      {
        krName: '스키어(Skier)',
        enName: 'Skier',
        value: 'SKIER',
        link: '/quest/SKIER',
      },
      {
        krName: '피스키퍼(Peacekeeper)',
        enName: 'Peacekeeper',
        value: 'PEACE_KEEPER',
        link: '/quest/PEACE_KEEPER',
      },
      {
        krName: '메카닉(Mechanic)',
        enName: 'Mechanic',
        value: 'MECHANIC',
        link: '/quest/MECHANIC',
      },
      {
        krName: '레그맨(Ragman)',
        enName: 'Ragman',
        value: 'RAG_MAN',
        link: '/quest/RAG_MAN',
      },
      {
        krName: '예거(Jaeger)',
        enName: 'Jaeger',
        value: 'JAEGER',
        link: '/quest/JAEGER',
      },
      {
        krName: '등대지기(Lightkeeper)',
        enName: 'Lightkeeper',
        value: 'LIGHT_KEEPER',
        link: '/quest/LIGHT_KEEPER',
      },
    ],
  },
  {
    value: 'ITEM',
    krName: '아이템',
    enName: 'Item',
    subMenu: [
      {
        krName: '무기(Weapon)',
        enName: 'Weapon',
        value: 'WEAPON',
        link: '/item/WEAPON',
      },
      {
        krName: '총알(Ammo)',
        enName: 'Ammo',
        value: 'AMMO',
        link: '/item/AMMO',
      },
      {
        krName: '방탄모(Head Wear)',
        enName: 'Head Wear',
        value: 'HEAD_WEAR',
        link: '/item/HEAD_WEAR',
      },
      {
        krName: '의료품(Medical)',
        enName: 'Medical',
        value: 'MEDICAL',
        link: '/item/MEDICAL',
      },
      {
        krName: '컨테이너(Container)',
        enName: 'Container',
        value: 'CONTAINER',
        link: '/item/CONTAINER',
      },
      {
        krName: '전술 조끼(Rig)',
        enName: 'Rig',
        value: 'RIG',
        link: '/item/RIG',
      },
      {
        krName: '방탄 조끼(Armor Vest)',
        enName: 'Armor Vest',
        value: 'ARMOR_VEST',
        link: '/item/ARMOR_VEST',
      },
      { krName: '키(Key)', enName: 'Key', value: 'KEY', link: '/item/KEY' },
      {
        krName: '헤드셋(Headset)',
        enName: 'Headset',
        value: 'HEADSET',
        link: '/item/HEADSET',
      },
      { krName: '가방(Bag)', enName: 'Bag', value: 'BAG', link: '/item/BAG' },
    ],
  },
  {
    value: 'INFO',
    krName: '정보',
    enName: 'Info',
    subMenu: [
      {
        krName: '보스(Boss)',
        enName: 'Boss',
        value: 'BOSS',
        link: '/info/BOSS',
      },
      {
        krName: '하이드아웃(Hideout)',
        enName: 'Hideout',
        value: 'HIDEOUT',
        link: '/info/HIDEOUT',
      },
    ],
  },
];
