export const QUEST_INFO = [
  {
    quest_id: 1,
    quest_name_kr: '슈팅캔',
    quest_name_en: 'Shootin Cans',
    quest_npc_value: 'PRAPOR',
    quest_objectives_en: ['One', 'Two', 'Three'],
    quest_objectives_kr: [
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">Utoys 기관총</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">AGS 유탄 발사기</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 5명 표적 제거',
    ],
    quest_rewards_en: ['one', 'two', 'three'],
    quest_rewards_kr: [
      '경험치 +1,600',
      '프라퍼 평판 +0.01',
      '13,000 루블',
      '모신 7.62*54R 볼트액션 소총(보병) x 1',
      '7.62*54mm R FMJ 탄약 팩 (20개) x 3',
    ],
    quest_required_kappa: false,
  },
  {
    quest_id: 2,
    quest_name_kr: '슈팅캔',
    quest_name_en: 'Shootin Cans',
    quest_npc_value: 'PRAPOR',
    quest_objectives_en: ['One', 'Two', 'Three'],
    quest_objectives_kr: [
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">Utoys 기관총</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">AGS 유탄 발사기</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 5명 표적 제거',
    ],
    quest_rewards_en: ['one', 'two', 'three'],
    quest_rewards_kr: [
      '경험치 +1,600',
      '프라퍼 평판 +0.01',
      '13,000 루블',
      '모신 7.62*54R 볼트액션 소총(보병) x 1',
      '7.62*54mm R FMJ 탄약 팩 (20개) x 3',
    ],
    quest_required_kappa: true,
  },
  {
    quest_id: 3,
    quest_name_kr: '슈팅캔',
    quest_name_en: 'Shootin Cans',
    quest_npc_value: 'PRAPOR',
    quest_objectives_en: ['One', 'Two', 'Three'],
    quest_objectives_kr: [
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">Utoys 기관총</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 <a href="/weapon" target=" _blank" class="highlight_quest">AGS 유탄 발사기</a> 찾기',
      '<a href="/map/GROUND_ZERO" target=" _blank" class="highlight_quest">그라운드 제로</a>에서 5명 표적 제거',
    ],
    quest_rewards_en: ['one', 'two', 'three'],
    quest_rewards_kr: [
      '경험치 +1,600',
      '프라퍼 평판 +0.01',
      '13,000 루블',
      '모신 7.62*54R 볼트액션 소총(보병) x 1',
      '7.62*54mm R FMJ 탄약 팩 (20개) x 3',
    ],
    quest_required_kappa: true,
  },
];
