/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 f.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function FModel(props) {
  const { nodes, materials } = useGLTF('./models/f.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <mesh
          geometry={nodes.instance_0.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0001.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0002.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0003.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0004.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0005.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0006.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0007.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0008.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0009.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0010.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0011.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0012.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0013.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0014.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0015.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0016.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0017.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0018.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0019.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0020.geometry}
          material={materials.__auto_}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0021.geometry}
          material={materials.__auto_1}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID678.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID678_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID684.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID684_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID692.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID692_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID698.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID698_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID704.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID704_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID710.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID710_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID716.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID716_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID722.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID722_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID728.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID728_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID734.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID734_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID740.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID740_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID746.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID746_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID752.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID752_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID758.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID758_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID764.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID764_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID770.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID770_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID776.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID776_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID782.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID782_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID788.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID788_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID794.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID794_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID800.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID800_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID806.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID806_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID812.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID812_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID818.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID818_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID824.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID824_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID830.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID830_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID836.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID836_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID842.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID842_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID848.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID848_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID854.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID854_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID860.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID860_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID866.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID866_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID872.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID872_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID878.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID878_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID884.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID884_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID890.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID890_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID896.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID896_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID902.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID902_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID908.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID908_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID914.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID914_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID920.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID920_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID926.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID926_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID932.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID932_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID938.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID938_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID944.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID944_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID950.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID950_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID956.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID956_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID962.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID962_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID968.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID968_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID974.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID974_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID980.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID980_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID986.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID986_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID992.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID992_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID998.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID998_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1004.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1004_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1010.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1010_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1016.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1016_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1022.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1022_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1028.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1028_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1034.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1034_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1040.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1040_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1046.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1046_1.geometry}
            material={materials.__auto_1}
          />
        </group>
        <mesh
          geometry={nodes.instance_0084.geometry}
          material={materials.__auto_6}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0085.geometry}
          material={materials.__auto_6}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0086.geometry}
          material={materials.__auto_6}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1070.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1070_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1076.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1076_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <mesh
          geometry={nodes.instance_0089.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0090.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0091.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0092.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0093.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0094.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0095.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0096.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0097.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0098.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0099.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0100.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0101.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0102.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0103.geometry}
          material={materials.__auto_11}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0104.geometry}
          material={materials.__auto_2}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0105.geometry}
          material={materials.__auto_2}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <mesh
          geometry={nodes.instance_0106.geometry}
          material={materials.__auto_2}
          position={[-1480.059, 40.595, -2999.63]}
        />
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1192.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1192_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <group position={[-1480.059, 40.595, -2999.63]}>
          <mesh geometry={nodes.ID1198.geometry} material={materials.__auto_} />
          <mesh
            geometry={nodes.ID1198_1.geometry}
            material={materials.__auto_2}
          />
        </group>
        <mesh
          geometry={nodes.instance_0109.geometry}
          material={materials.__auto_12}
          position={[-1480.059, 40.595, -2999.63]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/f.glb');
