import type { Metadata } from "next";
import Header from "@/components/header/header";
import { ChakraProvider, CSSReset } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <CSSReset />
          <Header />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
