export const KAPPA_IMAGE = "https://assets.tarkov.dev/5c093ca986f7740a1867ab12-8x.webp";

export const copyByLocale = {
  ko: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "좌표 또는 스크린샷 파일명을 입력하세요",
    map: "지도",
    floor: "층",
    coordinates: "좌표",
    height: "높이",
    quests: "퀘스트",
    questDetailPage: "상세 페이지",
    stories: "스토리",
    events: "이벤트",
    staticPoints: "위치",
    staticCategoryAll: "전체",
    staticCategories: {
      black_div_spawn: "블랙 디비전 스폰",
      bloodhounds_spawn: "블랙 디비전 스폰",
      boss_spawn: "보스 스폰",
      btr_stop: "BTR 정류장",
      cultist_spawn: "컬티스트 스폰",
      extract: "탈출구",
      goons_spawn: "군즈 스폰",
      pmc_spawn: "PMC 스폰",
      raider_spawn: "레이더 스폰",
      rogue_spawn: "로그 스폰",
      scav_spawn: "SCAV 스폰",
      sniper_spawn: "저격 스캐브 스폰",
      stationary_weapon: "고정 무기",
      transit: "Transits",
      transit_switch: "스위치",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "공용",
      unknown: "기타",
    },
    allOnOff: "ALL ON/OFF",
    save: "저장",
    saved: "저장되었습니다.",
    loginRequired: "로그인이 필요합니다.",
    noItems: "표시할 항목이 없습니다.",
    searchFilter: "검색",
    showMore: "더 보기",
    showLess: "접기",
    progress: "진행 중",
    completed: "완료",
    requirements: "선행 조건",
    objectives: "목표",
    objectiveLocation: "위치",
    requiredItems: "필요 아이템",
    rewards: "보상",
    minPlayerLevel: "최소 레벨",
    experience: "경험치",
    traderStanding: "상인 평판",
    rewardItems: "보상 아이템",
    unlocks: "해금",
    skills: "스킬",
    crafts: "제작",
    previous: "이전",
    next: "다음",
    noCoordinateInfo: "이 지도는 아직 위치 좌표 메타데이터가 없습니다.",
    noFloors: "표시할 지도 층 데이터가 없습니다.",
    guideTitle: "내 위치 찾기",
    guideModalTitle: "내 위치 찾기 가이드",
    guideAutoTitle: "프로그램 사용 시",
    guideAutoSteps: [
      "where-am-i.exe 파일을 실행합니다.",
      "이메일을 입력합니다.",
      "홈페이지에 로그인합니다.",
      "알맞은 지도를 선택한 뒤 스크린샷을 찍습니다.",
      "위치가 자동으로 지도에 표시됩니다.",
    ],
    guideManualTitle: "프로그램 미사용 시",
    guideManualSteps: [
      "PrintScreen 키로 스크린샷을 촬영합니다.",
      "스크린샷 파일명을 복사합니다.",
      "위치 확인 입력창에 붙여넣고 Locate를 누릅니다.",
    ],
    guideDownload: "프로그램 다운로드",
  },
  en: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "Enter coordinates or screenshot filename",
    map: "Map",
    floor: "Floor",
    coordinates: "Coordinates",
    height: "Height",
    quests: "Quests",
    questDetailPage: "Detail page",
    stories: "Stories",
    events: "Events",
    staticPoints: "Locations",
    staticCategoryAll: "All",
    staticCategories: {
      black_div_spawn: "Black Div Spawns",
      bloodhounds_spawn: "Bloodhounds",
      boss_spawn: "Boss Spawns",
      btr_stop: "BTR Stops",
      cultist_spawn: "Cultist Spawns",
      extract: "Extracts",
      goons_spawn: "Goons Spawns",
      pmc_spawn: "PMC Spawns",
      raider_spawn: "Raider Spawns",
      rogue_spawn: "Rogue Spawns",
      scav_spawn: "SCAV Spawns",
      sniper_spawn: "Sniper Spawns",
      stationary_weapon: "Stationary Weapons",
      transit: "Transits",
      transit_switch: "Transit Switches",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "Shared",
      unknown: "Other",
    },
    allOnOff: "ALL ON/OFF",
    save: "Save",
    saved: "Saved.",
    loginRequired: "Sign in required.",
    noItems: "No items to show.",
    searchFilter: "Search",
    showMore: "Show more",
    showLess: "Show less",
    progress: "Progress",
    completed: "Completed",
    requirements: "Requirements",
    objectives: "Objectives",
    objectiveLocation: "Location",
    requiredItems: "Required Items",
    rewards: "Rewards",
    minPlayerLevel: "Minimum Level",
    experience: "Experience",
    traderStanding: "Trader Standing",
    rewardItems: "Reward Items",
    unlocks: "Unlocks",
    skills: "Skills",
    crafts: "Crafts",
    previous: "Previous",
    next: "Next",
    noCoordinateInfo: "This map does not have coordinate metadata yet.",
    noFloors: "No map floor data is available.",
    guideTitle: "Find My Location",
    guideModalTitle: "Location Guide",
    guideAutoTitle: "With Program",
    guideAutoSteps: [
      "Run where-am-i.exe.",
      "Enter your email.",
      "Sign in to the website.",
      "Select the correct map and take a screenshot.",
      "Your location appears automatically.",
    ],
    guideManualTitle: "Without Program",
    guideManualSteps: [
      "Take a screenshot with PrintScreen.",
      "Copy the screenshot filename.",
      "Paste it into the location input and press Locate.",
    ],
    guideDownload: "Download Program",
  },
  ja: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "座標またはスクリーンショット名を入力",
    map: "マップ",
    floor: "階",
    coordinates: "座標",
    height: "高さ",
    quests: "クエスト",
    questDetailPage: "詳細ページ",
    stories: "ストーリー",
    events: "イベント",
    staticPoints: "位置",
    staticCategoryAll: "全体",
    staticCategories: {
      black_div_spawn: "Black Divスポーン",
      bloodhounds_spawn: "Bloodhounds",
      boss_spawn: "ボススポーン",
      btr_stop: "BTR停止地点",
      cultist_spawn: "カルトスポーン",
      extract: "脱出口",
      goons_spawn: "Goonsスポーン",
      pmc_spawn: "PMCスポーン",
      raider_spawn: "Raiderスポーン",
      rogue_spawn: "Rogueスポーン",
      scav_spawn: "SCAVスポーン",
      sniper_spawn: "スナイパースポーン",
      stationary_weapon: "固定武器",
      transit: "移動ルート",
      transit_switch: "移動スイッチ",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "共通",
      unknown: "その他",
    },
    allOnOff: "ALL ON/OFF",
    save: "保存",
    saved: "保存しました。",
    loginRequired: "ログインが必要です。",
    noItems: "表示する項目がありません。",
    searchFilter: "検索",
    showMore: "もっと見る",
    showLess: "閉じる",
    progress: "進行中",
    completed: "完了",
    requirements: "前提条件",
    objectives: "目標",
    objectiveLocation: "位置",
    requiredItems: "必要アイテム",
    rewards: "報酬",
    minPlayerLevel: "必要レベル",
    experience: "経験値",
    traderStanding: "トレーダー評価",
    rewardItems: "報酬アイテム",
    unlocks: "アンロック",
    skills: "スキル",
    crafts: "制作",
    previous: "前",
    next: "次",
    noCoordinateInfo: "このマップにはまだ座標メタデータがありません。",
    noFloors: "表示できるフロアデータがありません。",
    guideTitle: "位置確認",
    guideModalTitle: "位置確認ガイド",
    guideAutoTitle: "プログラム使用時",
    guideAutoSteps: [
      "where-am-i.exeを実行します。",
      "メールアドレスを入力します。",
      "サイトにログインします。",
      "正しいマップを選び、スクリーンショットを撮ります。",
      "位置が自動的に表示されます。",
    ],
    guideManualTitle: "プログラム未使用時",
    guideManualSteps: [
      "PrintScreenでスクリーンショットを撮影します。",
      "スクリーンショットのファイル名をコピーします。",
      "入力欄に貼り付けてLocateを押します。",
    ],
    guideDownload: "プログラムダウンロード",
  },
} as const;

export type LiveMapCopy = (typeof copyByLocale)[keyof typeof copyByLocale];
