export const KAPPA_IMAGE = "https://assets.tarkov.dev/5c093ca986f7740a1867ab12-8x.webp";

export const copyByLocale = {
  ko: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "좌표 또는 스크린샷 파일명을 입력하세요",
    map: "지도",
    floor: "층",
    coordinates: "좌표",
    height: "높이",
    quests: "퀘스트",
    stories: "스토리",
    events: "이벤트",
    staticPoints: "위치",
    staticCategoryAll: "전체",
    staticCategories: {
      extract: "탈출구",
      stationary_weapon: "고정 무기",
      transit: "이동 경로",
      transit_switch: "이동 스위치",
    },
    allOnOff: "ALL ON/OFF",
    save: "저장",
    saved: "저장되었습니다.",
    loginRequired: "로그인이 필요합니다.",
    noItems: "표시할 항목이 없습니다.",
    searchFilter: "검색",
    showMore: "더 보기",
    showLess: "접기",
    progress: "진행 중",
    completed: "완료",
    requirements: "선행 조건",
    objectives: "목표",
    requiredItems: "필요 아이템",
    rewards: "보상",
    minPlayerLevel: "최소 레벨",
    experience: "경험치",
    traderStanding: "상인 평판",
    rewardItems: "보상 아이템",
    unlocks: "해금",
    skills: "스킬",
    crafts: "제작",
    previous: "이전",
    next: "다음",
    noCoordinateInfo: "이 지도는 아직 위치 좌표 메타데이터가 없습니다.",
    noFloors: "표시할 지도 층 데이터가 없습니다.",
    guideTitle: "내 위치 찾기",
    guide:
      "where-am-i 프로그램에서 전달된 위치가 자동으로 반영됩니다. 직접 사용할 때는 스크린샷 파일명을 붙여넣고 Locate를 누르세요.",
  },
  en: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "Enter coordinates or screenshot filename",
    map: "Map",
    floor: "Floor",
    coordinates: "Coordinates",
    height: "Height",
    quests: "Quests",
    stories: "Stories",
    events: "Events",
    staticPoints: "Locations",
    staticCategoryAll: "All",
    staticCategories: {
      extract: "Extracts",
      stationary_weapon: "Stationary Weapons",
      transit: "Transits",
      transit_switch: "Transit Switches",
    },
    allOnOff: "ALL ON/OFF",
    save: "Save",
    saved: "Saved.",
    loginRequired: "Sign in required.",
    noItems: "No items to show.",
    searchFilter: "Search",
    showMore: "Show more",
    showLess: "Show less",
    progress: "Progress",
    completed: "Completed",
    requirements: "Requirements",
    objectives: "Objectives",
    requiredItems: "Required Items",
    rewards: "Rewards",
    minPlayerLevel: "Minimum Level",
    experience: "Experience",
    traderStanding: "Trader Standing",
    rewardItems: "Reward Items",
    unlocks: "Unlocks",
    skills: "Skills",
    crafts: "Crafts",
    previous: "Previous",
    next: "Next",
    noCoordinateInfo: "This map does not have coordinate metadata yet.",
    noFloors: "No map floor data is available.",
    guideTitle: "Find My Location",
    guide:
      "Locations sent by the where-am-i program appear automatically. To use it manually, paste the screenshot filename and press Locate.",
  },
  ja: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "座標またはスクリーンショット名を入力",
    map: "マップ",
    floor: "階",
    coordinates: "座標",
    height: "高さ",
    quests: "クエスト",
    stories: "ストーリー",
    events: "イベント",
    staticPoints: "位置",
    staticCategoryAll: "全体",
    staticCategories: {
      extract: "脱出口",
      stationary_weapon: "固定武器",
      transit: "移動ルート",
      transit_switch: "移動スイッチ",
    },
    allOnOff: "ALL ON/OFF",
    save: "保存",
    saved: "保存しました。",
    loginRequired: "ログインが必要です。",
    noItems: "表示する項目がありません。",
    searchFilter: "検索",
    showMore: "もっと見る",
    showLess: "閉じる",
    progress: "進行中",
    completed: "完了",
    requirements: "前提条件",
    objectives: "目標",
    requiredItems: "必要アイテム",
    rewards: "報酬",
    minPlayerLevel: "必要レベル",
    experience: "経験値",
    traderStanding: "トレーダー評価",
    rewardItems: "報酬アイテム",
    unlocks: "アンロック",
    skills: "スキル",
    crafts: "制作",
    previous: "前",
    next: "次",
    noCoordinateInfo: "このマップにはまだ座標メタデータがありません。",
    noFloors: "表示できるフロアデータがありません。",
    guideTitle: "位置確認",
    guide:
      "where-am-iプログラムから送信された位置は自動で反映されます。手動ではスクリーンショット名を貼り付けてLocateを押してください。",
  },
} as const;

export type LiveMapCopy = (typeof copyByLocale)[keyof typeof copyByLocale];
