export const KAPPA_IMAGE = "https://assets.tarkov.dev/5c093ca986f7740a1867ab12-8x.webp";

export const copyByLocale = {
  ko: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "좌표 또는 스크린샷 파일명을 입력하세요",
    map: "지도",
    floor: "층",
    coordinates: "좌표",
    height: "높이",
    quests: "퀘스트",
    questDetailPage: "상세 페이지",
    stories: "스토리",
    events: "이벤트",
    staticPoints: "위치",
    collapseSpawnPanel: "스폰 패널 접기",
    expandSpawnPanel: "스폰 패널 펼치기",
    collapseQuestPanel: "퀘스트 패널 접기",
    expandQuestPanel: "퀘스트 패널 펼치기",
    lockAutoMove: "자동 화면 이동 잠금",
    unlockAutoMove: "자동 화면 이동 잠금 해제",
    autoMoveLocked: "자동 이동 잠금",
    autoMoveUnlocked: "자동 이동 허용",
    hideMapLabels: "보스·탈출구 이름 숨기기",
    showMapLabels: "보스·탈출구 이름 표시하기",
    mapLabelsShown: "이름 표시",
    mapLabelsHidden: "이름 숨김",
    simplifyMarkers: "마커 간소화 켜기",
    showDetailedMarkers: "상세 마커로 보기",
    markersSimplified: "간편 표시",
    markersDetailed: "상세 표시",
    enableEyeComfort: "차분한 모드 켜기",
    disableEyeComfort: "차분한 모드 끄기",
    eyeComfortOn: "차분한 모드",
    eyeComfortOff: "기본 모드",
    drawingTools: "지도 그리기 도구",
    drawing: "그리기",
    rotateMap: "지도 시계 방향으로 90도 회전",
    rotation: "회전",
    viewSettings: "보기 설정",
    panMap: "지도 이동",
    redPen: "빨간 펜",
    bluePen: "파란 펜",
    eraser: "지우개",
    undoDrawing: "마지막 작업 취소",
    clearDrawing: "그림 전체 삭제",
    clearDrawingConfirm: "현재 지도와 층에 그린 그림을 모두 삭제할까요?",
    staticCategoryAll: "전체",
    staticCategories: {
      black_div_spawn: "블랙 디비전 스폰",
      bloodhounds_spawn: "블랙 디비전 스폰",
      boss_spawn: "보스 스폰",
      btr_stop: "BTR 정류장",
      cultist_spawn: "컬티스트 스폰",
      extract: "탈출구",
      goons_spawn: "군즈 스폰",
      pmc_spawn: "PMC 스폰",
      raider_spawn: "레이더 스폰",
      rogue_spawn: "로그 스폰",
      scav_spawn: "SCAV 스폰",
      sniper_spawn: "저격 스캐브 스폰",
      stationary_weapon: "고정 무기",
      transit: "Transits",
      transit_switch: "스위치",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "공용",
      unknown: "기타",
    },
    allOnOff: "ALL ON/OFF",
    save: "저장",
    saved: "저장되었습니다.",
    loginRequired: "로그인이 필요합니다.",
    noItems: "표시할 항목이 없습니다.",
    searchFilter: "검색",
    showMore: "더 보기",
    showLess: "접기",
    progress: "진행 중",
    completed: "완료",
    requirements: "선행 조건",
    objectives: "목표",
    objectiveLocation: "위치",
    requiredItems: "필요 아이템",
    requiredKeys: "필요 열쇠",
    rewards: "보상",
    minPlayerLevel: "최소 레벨",
    experience: "경험치",
    traderStanding: "상인 평판",
    rewardItems: "보상 아이템",
    unlocks: "해금",
    skills: "스킬",
    crafts: "제작",
    previous: "이전",
    next: "다음",
    noCoordinateInfo: "이 지도는 아직 위치 좌표 메타데이터가 없습니다.",
    noFloors: "표시할 지도 층 데이터가 없습니다.",
    guideTitle: "내 위치 찾기",
    guideModalTitle: "내 위치 찾기 가이드",
    guideScreenshotTitle: "스크린샷 촬영 전 확인",
    guideScreenshotNotice: "스크린샷은 Windows 캡처 도구나 Steam의 캡처 기능이 아닌 Escape from Tarkov 게임 안의 스크린샷 기능으로 촬영해야 합니다.",
    guideSteamNotice: "기본 스크린샷 키는 Print Screen입니다. Steam 버전에서 게임 내 스크린샷이 생성되지 않으면, 게임 키 설정에서 스크린샷 기능을 현재 사용하지 않는 다른 키로 변경해 주세요.",
    guideAutoTitle: "프로그램 사용 시",
    guideAutoSteps: [
      "where-am-i.exe 파일을 실행합니다.",
      "이메일을 입력합니다.",
      "홈페이지에 로그인합니다.",
      "알맞은 지도를 선택한 뒤 게임 안에서 스크린샷을 찍습니다.",
      "위치가 자동으로 지도에 표시됩니다.",
    ],
    guideManualTitle: "프로그램 미사용 시",
    guideManualSteps: [
      "게임 안에서 Print Screen을 눌러 촬영합니다. Steam 버전에서 동작하지 않으면 게임 내 스크린샷 키를 사용하지 않는 다른 키로 변경합니다.",
      "스크린샷 파일명을 복사합니다.",
      "위치 확인 입력창에 붙여넣고 Locate를 누릅니다.",
    ],
    guideDownload: "프로그램 다운로드",
  },
  en: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "Enter coordinates or screenshot filename",
    map: "Map",
    floor: "Floor",
    coordinates: "Coordinates",
    height: "Height",
    quests: "Quests",
    questDetailPage: "Detail page",
    stories: "Stories",
    events: "Events",
    staticPoints: "Locations",
    collapseSpawnPanel: "Collapse spawn panel",
    expandSpawnPanel: "Expand spawn panel",
    collapseQuestPanel: "Collapse quest panel",
    expandQuestPanel: "Expand quest panel",
    lockAutoMove: "Lock automatic map movement",
    unlockAutoMove: "Unlock automatic map movement",
    autoMoveLocked: "Auto move locked",
    autoMoveUnlocked: "Auto move enabled",
    hideMapLabels: "Hide boss and extraction names",
    showMapLabels: "Show boss and extraction names",
    mapLabelsShown: "Names shown",
    mapLabelsHidden: "Names hidden",
    simplifyMarkers: "Simplify markers",
    showDetailedMarkers: "Show detailed markers",
    markersSimplified: "Simple markers",
    markersDetailed: "Detailed markers",
    enableEyeComfort: "Enable muted colors",
    disableEyeComfort: "Disable muted colors",
    eyeComfortOn: "Muted colors",
    eyeComfortOff: "Default mode",
    drawingTools: "Map drawing tools",
    drawing: "Draw",
    rotateMap: "Rotate map 90 degrees clockwise",
    rotation: "Rotation",
    viewSettings: "View settings",
    panMap: "Pan map",
    redPen: "Red pen",
    bluePen: "Blue pen",
    eraser: "Eraser",
    undoDrawing: "Undo last action",
    clearDrawing: "Clear drawing",
    clearDrawingConfirm: "Clear every drawing on this map floor?",
    staticCategoryAll: "All",
    staticCategories: {
      black_div_spawn: "Black Div Spawns",
      bloodhounds_spawn: "Bloodhounds",
      boss_spawn: "Boss Spawns",
      btr_stop: "BTR Stops",
      cultist_spawn: "Cultist Spawns",
      extract: "Extracts",
      goons_spawn: "Goons Spawns",
      pmc_spawn: "PMC Spawns",
      raider_spawn: "Raider Spawns",
      rogue_spawn: "Rogue Spawns",
      scav_spawn: "SCAV Spawns",
      sniper_spawn: "Sniper Spawns",
      stationary_weapon: "Stationary Weapons",
      transit: "Transits",
      transit_switch: "Transit Switches",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "Shared",
      unknown: "Other",
    },
    allOnOff: "ALL ON/OFF",
    save: "Save",
    saved: "Saved.",
    loginRequired: "Sign in required.",
    noItems: "No items to show.",
    searchFilter: "Search",
    showMore: "Show more",
    showLess: "Show less",
    progress: "Progress",
    completed: "Completed",
    requirements: "Requirements",
    objectives: "Objectives",
    objectiveLocation: "Location",
    requiredItems: "Required Items",
    requiredKeys: "Required Keys",
    rewards: "Rewards",
    minPlayerLevel: "Minimum Level",
    experience: "Experience",
    traderStanding: "Trader Standing",
    rewardItems: "Reward Items",
    unlocks: "Unlocks",
    skills: "Skills",
    crafts: "Crafts",
    previous: "Previous",
    next: "Next",
    noCoordinateInfo: "This map does not have coordinate metadata yet.",
    noFloors: "No map floor data is available.",
    guideTitle: "Find My Location",
    guideModalTitle: "Location Guide",
    guideScreenshotTitle: "Before taking a screenshot",
    guideScreenshotNotice: "Use the screenshot function inside Escape from Tarkov, not a Windows capture tool or Steam's screenshot feature.",
    guideSteamNotice: "The default in-game screenshot key is Print Screen. If the Steam version does not create an in-game screenshot, rebind the screenshot action in the game settings to another unused key.",
    guideAutoTitle: "With Program",
    guideAutoSteps: [
      "Run where-am-i.exe.",
      "Enter your email.",
      "Sign in to the website.",
      "Select the correct map and take a screenshot inside the game.",
      "Your location appears automatically.",
    ],
    guideManualTitle: "Without Program",
    guideManualSteps: [
      "Press Print Screen inside the game. If it does not work on the Steam version, rebind the in-game screenshot action to another unused key.",
      "Copy the screenshot filename.",
      "Paste it into the location input and press Locate.",
    ],
    guideDownload: "Download Program",
  },
  ja: {
    title: "Live Map",
    locate: "Locate",
    placeholder: "座標またはスクリーンショット名を入力",
    map: "マップ",
    floor: "階",
    coordinates: "座標",
    height: "高さ",
    quests: "クエスト",
    questDetailPage: "詳細ページ",
    stories: "ストーリー",
    events: "イベント",
    staticPoints: "位置",
    collapseSpawnPanel: "スポーンパネルを閉じる",
    expandSpawnPanel: "スポーンパネルを開く",
    collapseQuestPanel: "クエストパネルを閉じる",
    expandQuestPanel: "クエストパネルを開く",
    lockAutoMove: "マップの自動移動をロック",
    unlockAutoMove: "マップの自動移動ロックを解除",
    autoMoveLocked: "自動移動ロック中",
    autoMoveUnlocked: "自動移動を許可",
    hideMapLabels: "ボス・脱出口名を非表示",
    showMapLabels: "ボス・脱出口名を表示",
    mapLabelsShown: "名前を表示中",
    mapLabelsHidden: "名前を非表示",
    simplifyMarkers: "マーカーを簡略表示",
    showDetailedMarkers: "詳細マーカーを表示",
    markersSimplified: "簡易表示",
    markersDetailed: "詳細表示",
    enableEyeComfort: "落ち着いたカラーモードを有効化",
    disableEyeComfort: "落ち着いたカラーモードを無効化",
    eyeComfortOn: "落ち着いたカラー",
    eyeComfortOff: "標準モード",
    drawingTools: "マップ描画ツール",
    drawing: "描画",
    rotateMap: "マップを時計回りに90度回転",
    rotation: "回転",
    viewSettings: "表示設定",
    panMap: "マップ移動",
    redPen: "赤ペン",
    bluePen: "青ペン",
    eraser: "消しゴム",
    undoDrawing: "最後の操作を元に戻す",
    clearDrawing: "描画をすべて削除",
    clearDrawingConfirm: "このマップ階層の描画をすべて削除しますか？",
    staticCategoryAll: "全体",
    staticCategories: {
      black_div_spawn: "Black Divスポーン",
      bloodhounds_spawn: "Bloodhounds",
      boss_spawn: "ボススポーン",
      btr_stop: "BTR停止地点",
      cultist_spawn: "カルトスポーン",
      extract: "脱出口",
      goons_spawn: "Goonsスポーン",
      pmc_spawn: "PMCスポーン",
      raider_spawn: "Raiderスポーン",
      rogue_spawn: "Rogueスポーン",
      scav_spawn: "SCAVスポーン",
      sniper_spawn: "スナイパースポーン",
      stationary_weapon: "固定武器",
      transit: "移動ルート",
      transit_switch: "移動スイッチ",
    },
    staticFactions: {
      pmc: "PMC",
      scav: "Scav",
      shared: "共通",
      unknown: "その他",
    },
    allOnOff: "ALL ON/OFF",
    save: "保存",
    saved: "保存しました。",
    loginRequired: "ログインが必要です。",
    noItems: "表示する項目がありません。",
    searchFilter: "検索",
    showMore: "もっと見る",
    showLess: "閉じる",
    progress: "進行中",
    completed: "完了",
    requirements: "前提条件",
    objectives: "目標",
    objectiveLocation: "位置",
    requiredItems: "必要アイテム",
    requiredKeys: "必要な鍵",
    rewards: "報酬",
    minPlayerLevel: "必要レベル",
    experience: "経験値",
    traderStanding: "トレーダー評価",
    rewardItems: "報酬アイテム",
    unlocks: "アンロック",
    skills: "スキル",
    crafts: "制作",
    previous: "前",
    next: "次",
    noCoordinateInfo: "このマップにはまだ座標メタデータがありません。",
    noFloors: "表示できるフロアデータがありません。",
    guideTitle: "位置確認",
    guideModalTitle: "位置確認ガイド",
    guideScreenshotTitle: "スクリーンショット撮影前の確認",
    guideScreenshotNotice: "WindowsのキャプチャーツールやSteamのスクリーンショット機能ではなく、Escape from Tarkovゲーム内のスクリーンショット機能を使用してください。",
    guideSteamNotice: "ゲーム内スクリーンショットの初期キーはPrint Screenです。Steam版でゲーム内スクリーンショットが作成されない場合は、ゲーム設定でスクリーンショット機能を未使用の別のキーに変更してください。",
    guideAutoTitle: "プログラム使用時",
    guideAutoSteps: [
      "where-am-i.exeを実行します。",
      "メールアドレスを入力します。",
      "サイトにログインします。",
      "正しいマップを選び、ゲーム内でスクリーンショットを撮ります。",
      "位置が自動的に表示されます。",
    ],
    guideManualTitle: "プログラム未使用時",
    guideManualSteps: [
      "ゲーム内でPrint Screenを押して撮影します。Steam版で動作しない場合は、ゲーム内スクリーンショット機能を未使用の別のキーに変更します。",
      "スクリーンショットのファイル名をコピーします。",
      "入力欄に貼り付けてLocateを押します。",
    ],
    guideDownload: "プログラムダウンロード",
  },
} as const;

export type LiveMapCopy = (typeof copyByLocale)[keyof typeof copyByLocale];
